
apiVersion: intersystems.com/v1alpha1
kind: IrisCluster
metadata:
  name: htapirisdb
spec:
  passwordHash: '071e3aa0c8810f91eefd8f074e3768b06c66308a,v7mf8dt5'
  licenseKeySecret:
    name: iris-key-secret
  topology:
    data:
      shards: 1
      mirrored: false
      image: store/intersystems/iris-community:2020.4.0.521.0 
      podTemplate:
        spec:
          imagePullSecrets:
          - name: dockerhub-secret
          selector:
            matchLabels:
              app: htapirisdb
      updateStrategy:
        type: RollingUpdate
      storage:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 20G
        storageClassName: data-storage-class
