apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deployment
  labels:
    app: ui-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui-pod
  template:
    metadata:
      labels:
        app: ui-pod
    spec:
      nodeSelector:
        speedtest/node-type: master-ui
      containers:
      - name: ui-container
        image: intersystemsdc/irisdemo-demo-htap:ui-version-2.5.3
        resources:
          requests:
              cpu: 0.5
              memory: 512M
        ports:
        - containerPort: 4200