
apiVersion: intersystems.com/v1alpha1
kind: IrisCluster
metadata:
  name: htapirisdb
spec:
  passwordHash: '071e3aa0c8810f91eefd8f074e3768b06c66308a,v7mf8dt5'
  licenseKeySecret:
    name: iris-key-secret
  topology:
    data:
      shards: 1
      mirrored: false
     image: intersystemsicm/iris:2020.3.0AA.331.0
      podTemplate:
        spec:
          imagePullSecrets:
            - name: dockerhub-secret
         selector:
           matchLabels:
             app: htapirisdb
          tolerations:
          - key: "iris-group"
            operator: "Equal"
            value: "true"
            effect: "NoSchedule"
      updateStrategy:
        type: RollingUpdate
      storage:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100G
        storageClassName: storage-class-iris-r5-2xlarge
  serviceTemplate:
    spec:
      type: LoadBalancer



