apiVersion: intersystems.com/v1alpha1
kind: IrisCluster
metadata:
  name: htapirisdb
spec:
  passwordHash: '071e3aa0c8810f91eefd8f074e3768b06c66308a,v7mf8dt5'
  topology:
    data:
      shards: <SHARDS>
      mirrored: <MIRROR>
      image: intersystemsdc/irisdemo-base-irisdb-community:version-1.4
      podTemplate:
        spec:
          nodeSelector:
            node-label: iris
          imagePullSecrets:
          - name: dockerhub-secret
          selector:
            matchLabels:
              app: htapirisdb
      updateStrategy:
        type: RollingUpdate
      storage:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: <STORAGE_SIZE>
        storageClassName: data-storage-class
