apiVersion: intersystems.com/v1alpha1
kind: IrisCluster
metadata:
  name: htapirisdb
spec:
  passwordHash: '071e3aa0c8810f91eefd8f074e3768b06c66308a,v7mf8dt5'
  licenseKeySecret:
    name: iris-key-secret
  configSource:
    name: iris-cpf
  topology:
    data:
      shards: <SHARDS>
      mirrored: <MIRROR>
      image: angellopezque/iko:iris-2020.4.0.524.0
      preferredZones:
        - us-east-2b
        - us-east-2c
      podTemplate:
        spec:
          nodeSelector:
            speedtest/node-type: iris
          imagePullSecrets:
          - name: dockerhub-secret
          resources:
            requests:
              cpu: <CPUS>
          selector:
            matchLabels:
              app: htapirisdb
      updateStrategy:
        type: RollingUpdate
      storageDB:
      # storage:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: <STORAGE_SIZE>G
        storageClassName: ssd-storage-class-normal
      storageWIJ:
        resources:
          requests:
            storage: <WIJ_STORAGE_SIZE>G
        storageClassName: ssd-storage-class-slow
      storageJournal1:
        resources:
          requests:
            storage: <J1_STORAGE_SIZE>G
        storageClassName: ssd-storage-class-slow
      storageJournal2:
        resources:
          requests:
            storage: <J2_STORAGE_SIZE>G
        storageClassName: ssd-storage-class-fast
